grenade
re1nex/portan-ignis pull request #332
Opened 2020-05-20 15:29 UTC by MethaHardworker

- grenade on levels
- grenade in inventory
- flying grenade

2020-05-20 16:33 UTC, PinkOink requested changes
- Почему, если у меня есть 3 гранаты, они все вылетают при нажатии G?
- Подбираемые гранаты должны шевелиться, как сердца, рычаги и тд.
- Пусть граната побольше освещает, до того, как вспыхнет на полную
- Повернутая граната может дымить не в ту сторону.

2020-05-21 10:30 UTC, re1nex requested changes
- сделать фото в инвентаре побольше 
- поправить баг с падением сквозь платформы

2020-05-22 14:56 UTC, PinkOink approved these changes

2020-05-24 10:34 UTC, re1nex approved these changes

2020-05-24 10:46 UTC, merged

2020-07-12 15:41 UTC, mitenevav commented
> * grenade on levels
зочем?